### ISSUE TITLE
Can I contribute?

### ISSUE THREAD

**Issue by samdoj** [jferrettiboke/react-stripe#1]
Hi there,  I've been using React for awhile now, and I'd like to get in on the ground floor of your project.  I see you haven't written any code yet, and I'd love to help you implement the Stripe payment system in React.  I feel like it should actually be reasonably straightforward. :)  Can we chat about what kind of functionality you want to include?

**Comment by jferrettiboke** [comment]
Hi @samdoj! Reach me out on Twitter and send me a DM.
